version: "3"
services: 
    nginx:
        ports: 
            - "3000:80"

    sample-node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app:ro
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=nickgdev
            - MONGO_PASSWORD=arapahoe22
            - SESSION_SECRET=catch22
        command: npm run dev 
        
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=nickgdev
            - MONGO_INITDB_ROOT_PASSWORD=arapahoe22
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db: