version: "3"
services: 
    nginx:
        image: nginx:stable-alpine 
        ports: 
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    sample-node-app:
        build: .
        environment: 
            - PORT=3000
        depends_on: 
            - mongo

    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=nickgdev
            - MONGO_INITDB_ROOT_PASSWORD=arapahoe22
        volumes:
            - mongo-db:/data/db

    redis: 
        image: redis

volumes:
    mongo-db: